Repository craftyjs/Crafty, pull requests merged in 2018-09, with the labels that each got.

#1189 [ Feature ] Support Assets encoded in Data URI
  package.json
  src/core/loader.js
  src/core/utility.js
  tests/unit/lib/qunit.css
  tests/unit/lib/qunit.js
Labels: kind: enhancement

#1187 Updated the license year
  LICENSE
  README.md
Labels: topic: meta

#1191 Add a promise-driven initAsync method
  src/core/core.js
Labels: api: extension, kind: enhancement, topic: core
